//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ehealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment
    {
        public int id { get; set; }
        public int doctor_id { get; set; }
        public int patient_id { get; set; }
        public System.DateTime apptDate { get; set; }
        public System.DateTime apptStartTime { get; set; }
        public System.DateTime apptEndTime { get; set; }
        public string isCancelled { get; set; }
    
        public virtual doctor doctor { get; set; }
        public virtual patient patient { get; set; }
    }
}
