//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ehealth.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doctor()
        {
            this.appointments = new HashSet<appointment>();
            this.patients = new HashSet<patient>();
            this.patients1 = new HashSet<patient>();
        }
    
        public int id { get; set; }

        [Display(Name ="Doctor Name")]
        public string doctorName { get; set; }
        public int speciality_id { get; set; }
        [Display(Name ="Available Time")]
        public System.DateTime availableTime { get; set; }
        [Display(Name ="Available Date")]
        public System.DateTime availableDate { get; set; }
        [Display(Name ="Doctor Contact")]
        public string doctorContact { get; set; }
        [Display(Name ="Doctor Email")]
        public string doctorEmail { get; set; }
        public int user_id { get; set; }
        
        public string username { get; set; }
        public string password { get; set; }
        [Display(Name = "Role Name")]
        public int role_id { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<appointment> appointments { get; set; }
        public virtual speciality speciality { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<patient> patients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<patient> patients1 { get; set; }
    }
}
