//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ehealth.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EhealthContext : DbContext
    {
        public EhealthContext()
            : base("name=EhealthContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<appointment> appointments { get; set; }
        public virtual DbSet<doctor> doctors { get; set; }
        public virtual DbSet<history> histories { get; set; }
        public virtual DbSet<hospital> hospitals { get; set; }
        public virtual DbSet<patient> patients { get; set; }
        public virtual DbSet<speciality> specialities { get; set; }
        public virtual DbSet<test_results> test_results { get; set; }
        public virtual DbSet<test_types> test_types { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
