//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ehealth.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public patient()
        {
            this.appointments = new HashSet<appointment>();
            this.histories = new HashSet<history>();
            this.test_results1 = new HashSet<test_results>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "Enter Patient NHS Number")]
        public string patientNhsNo { get; set; }
        [Required(ErrorMessage = "Enter Patient Name")]
        public string patientName { get; set; }
        [Required(ErrorMessage = "Enter Patient Contact")]
        public string patientContact { get; set; }
        [Required(ErrorMessage = "Enter Patient Email")]
        public string patientEmail { get; set; }
        [Required(ErrorMessage = "Enter Patient DOB")]
        public System.DateTime patientDob { get; set; }
        [Required(ErrorMessage = "Enter Patient Adress")]
        public string patientAddress { get; set; }
        public int hospital_id { get; set; }
        public System.DateTime arrivalTime { get; set; }
        public System.DateTime arrivalDate { get; set; }
        public int history_id { get; set; }
        public int test_result_id { get; set; }
        public int test_type_id { get; set; }
        public int doctor_id { get; set; }
        public string followUps { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<appointment> appointments { get; set; }
        public virtual doctor doctor { get; set; }
        public virtual doctor doctor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<history> histories { get; set; }
        public virtual history history { get; set; }
        public virtual hospital hospital { get; set; }
        public virtual test_results test_results { get; set; }
        public virtual test_types test_types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<test_results> test_results1 { get; set; }
    }
}
